# Linear Regression Algorithm from Scratch - Gradient Descent method

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

Regression function: $ \hat{y} = w x_i + b $.

Loss function: $ MSE = J(w, b) = \frac{1}{n} \sum_{i = 1}^{n} (y_i - (w x_i + b))^2 $

Gradient: $ J'(w, b)
= \begin{bmatrix}
    \frac{d J}{d w} \\
    \frac{d J}{d b} \\
\end{bmatrix}
= \begin{bmatrix}
    \frac{1}{n} \sum_{i=1}^{n} -2 x_i (y_i - (w x_i + b)) \\
    \frac{1}{n} \sum_{i=1}^{n} -2 (y_i - (w x_i + b)) \\
\end{bmatrix} $.

In [2]:
def mse(y_pred, y_true):
    return np.sum((y_pred - y_true)**2)

In [3]:
class LinearRegression:
    def __init__(self, n_iters, learning_rate = 0.0001):
        self.n_iters = n_iters
        self.learning_rate = learning_rate
        
        self.weights = None
        self.bias = None
        
    
    def fit(self, X, y):
        n_samples, n_feats = X.shape
        
        self.weights = np.zeros(n_feats)
        self.bias = 0
        
        for _ in range(self.n_iters):
            y_pred = X.dot(self.weights) + self.bias
    
            dw = (1 / n_samples) * (X.T.dot(y_pred - y))
            db = (1 / n_samples) * np.sum(y_pred - y)

            self.weights -= self.learning_rate * dw
            self.bias -= self.learning_rate * db
    
    def predict(self, X):
        return X.dot(self.weights) + self.bias

In [4]:
n_features = 5
n_samples = 1000

X = np.random.randint(-30, 30, (n_samples, n_features))

real_coeffs = np.random.randint(-6, 10, n_features)
real_bias = np.random.randint(-10, 10)
print(real_coeffs, real_bias)

y = X.dot(real_coeffs) + real_bias + np.random.normal(loc=5.0, scale=10.0, size=n_samples)

[5 8 1 7 7] 0


In [5]:
lr = LinearRegression(n_iters=10000, learning_rate=0.0002)
lr.fit(X, y)

In [6]:
lr.weights, lr.bias

(array([4.99603679, 7.99243984, 1.00590159, 7.00463369, 6.98721279]),
 4.351487001859601)

In [7]:
y_pred = lr.predict(X)
mse(y_pred, y)

100491.72028657171

In [8]:
lr.weights, real_coeffs

(array([4.99603679, 7.99243984, 1.00590159, 7.00463369, 6.98721279]),
 array([5, 8, 1, 7, 7]))